ame: Release (main)

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: pnpm i
      - run: pnpm test
      - run: pnpm run lint
      - run: pnpm run stylelint
      - run: pnpm run typecheck

  publish-npm:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: pnpm i

      - name: Set registry
        run: |
          pnpm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  create-release:
    needs: publish-pnpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}